# Generated by Django 3.2.2 on 2021-05-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_portfolio_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolio",
            options={"ordering": ("created_at",), "verbose_name": "Portfolio"},
        ),
    ]
