# Generated by Django 3.2.2 on 2021-05-13 18:23

from django.db import migrations, models
import djlime.utils


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_portfolio_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="main_image",
            field=models.ImageField(
                blank=True,
                help_text="recommended size 1000x665",
                null=True,
                upload_to=djlime.utils.get_file_path,
                verbose_name="main image",
            ),
        ),
    ]
