# Generated by Django 3.2.2 on 2021-05-13 05:51

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djlime.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("show", models.BooleanField(default=True, verbose_name="show")),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("enabled", models.BooleanField(default=True, verbose_name="enabled")),
                ("title", models.CharField(max_length=100, verbose_name="name")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="recommended size 1000x665",
                        null=True,
                        upload_to=djlime.utils.get_file_path,
                        verbose_name="image",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.portfolio",
                        verbose_name="portfolio",
                    ),
                ),
            ],
        ),
    ]
