# Generated by Django 3.2.2 on 2021-05-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
    ]
