# Generated by Django 3.2.2 on 2021-05-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_portfolio_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
    ]
